version: "3.9"

services:
  backend:
    build: ./detail-service
    container_name: auroramag-backend
    ports:
      - "3337:3337"
    env_file: .env
    depends_on:
      - bitmagnet
    restart: unless-stopped

  frontend:
    build: ./search-service
    container_name: auroramag-frontend
    ports:
      - "3336:3336"
      - "3335:3335"
    env_file: .env
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend
      - bitmagnet
    restart: unless-stopped

  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet
    ports:
      - "3333:3333"
      - "3334:3334/tcp"
      - "3334:3334/udp"
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./bitmagnet-config:/root/.config/bitmagnet
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
